###########################################################
# Script: training.py / train.py
# Description: Main configuration for deep learning downscaling.
# Input: ERA5 or LMDZ datasets (predictors), Precipitation or Temperature (targets).
# Output: Trained models (.pth) and losses saved in results/exp_name/.
###########################################################

general:
  verbose: true
  experiment: "unet_precip_linear"
  variable: "precip"  
  target: "mswep"    
  src: "era5"        
  model_type: "unet" 
  interpolation_type: "linear" 
  variables: ["z", "q", "t", "u", "v"]
  levels: [500, 700, 850]
  resolution: 2.0

training:
  learning_rate: 1e-3
  epochs: 100
  batch_size: 64
  loss_type: "bernoulli_gamma" 
  norm_mode: "gridbox"         
  early_stopping_max: 15

vit:
  emb_size: 128
  patch_size: 4
  num_layers: 4
  num_heads: 4
  dropout: 0.0

region:
  lon_min: -18
  lon_max: 0
  lat_min: 21
  lat_max: 37

dates:
  train:
    start: "1980-01-01"
    end: "2005-12-31"
  test:
    start: "2006-01-01"
    end: "2020-12-31"

paths:
  root_dir: "/home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data/"
  results_dir: "results/"
  shapefile_path: "/home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data/shapefiles/Morocco_shpfile/DA_REGIONS_12R.shp"
  era5_predictor_pattern: "era5ztquv/1979_2020/merged/{var}_1979-2020_levels.nc"
  mswep_path: "mswep/mswep_1979_2020.nc"
