project:
  main_config_path: "./temp/main/configs/unet1/config.yaml"

metric:
  name: "ac1"
  min_valid: 10

spatial:
  eval_domain: "land"   # "full_domain" | "morocco_shape" | "land"
  save_mask: true

  # utilisé si eval_domain = "morocco_shape"
  shapefile_path: null           # null => cfg.shapefile_path du main config

  # utilisé si eval_domain = "land"
  land_shapefile_path: null      # null => Natural Earth land polygons

plot:
  display_domain: "land"   # "morocco_shape" | "land"

data:
  prediction_path: null
  prediction_var: "air_temperature"
  prediction_units: null

  reference_path: null
  reference_var: null
  reference_units: null

time:
  use_test_period_from_main_config: true
  start_date: null
  end_date: null

output:
  save_netcdf: true
  save_summary_json: true
  save_summary_csv: true
