general:
  verbose: true
  experiment: cnn10_mse_temperature_test_cpu
  variable: temp
  target: lmdz35
  src: lmdz35
  model_type: cnn10
  interpolation_type: linear
  variables:
  - z
  - q
  - t
  - u
  - v
  levels:
  - 500
  - 700
  - 850
  - 1000
  resolution: 2.0
training:
  learning_rate: 1e-3
  epochs: 1
  batch_size: 64
  loss_type: mse
  norm_mode: gridbox
  early_stopping:
    enable: true
    max: 15
  LR_scheduler:
    enable: true
    patience: 5
    factor: 0.5
    min_lr: 1e-6
  gradient_clipping:
    enable: true
    value: 1.0
  weight_decay:
    enable: true
    value: 1e-4
  optimizer: adam
  dropout:
    enable: true
    value: 0.1
  scheduler:
    enable: false
    type: cosine
  group_norm:
    enable: true
    num_groups: 32
  validation:
    enable: true
    percentage: 0.1
cnn:
  mode: cnn10

lmdz_var_map:
  z: geop
  q: rhum
  t: temp
  u: vitu
  v: vitv
region:
  lon_min: -18
  lon_max: 0
  lat_min: 21
  lat_max: 36
dates:
  train:
    start: '1979-01-01'
    end: '2005-12-31'
  test:
    start: '2006-01-01'
    end: '2014-12-31'
paths:
  root_dir: /home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data/models/lmdz/r35
  results_dir: /srv/data/mohammad.elaabaribao/work/interns/y2026/temp/ds_temp_intern/temp/lmdz35Upscaled2degre_to_lmdz35/main/results/cnn
  shapefile_path: /home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data/shapefiles/Morocco_shpfile/DA_REGIONS_12R.shp
  lmdz35_predictor_pattern: /home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data/models/lmdz/r35/{lmdz_var}-hist.nc
  lmdz35_path: /home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data/models/lmdz/r35/temp-hist.nc
