project:
  main_config_path: "./temp/main/configs/unet/config.yaml"

metric:
  name: "rmse"
  strategy: "daily_first"         # "daily_first" or "mean_first"
  return_by_year: false
  min_valid: 10
  seasons: ["Annual", "DJF", "MAM", "JJA", "SON"]

data:
  prediction_path: null
  prediction_var: "air_temperature"
  prediction_units: null

  reference_path: null
  reference_var: null
  reference_units: null

time:
  use_test_period_from_main_config: true
  start_date: null
  end_date: null

output:
  save_netcdf: true
  save_summary_json: true
  save_summary_csv: true