###########################################################
# UNet configuration
###########################################################

general:
  verbose: true
  experiment: "unet1_lmdz35_to_lmdz35" # for "unet_temperature" or "unet1_temperature"
  variable: "temp"
  target: "lmdz35"
  src: "lmdz35"
  model_type: "unet1" # for "unet" or "unet1"
  interpolation_type: "linear"
  variables: ["z", "q", "t", "u", "v"]
  levels: [500, 700, 850, 1000]
  resolution: 2.0

training:
  learning_rate: 1e-3
  epochs: 30
  batch_size: 4 # le nombre d’exemples envoyés au modèle en une seule itération.
  loss_type: "gaussian" 
  norm_mode: "gridbox"         
  early_stopping:
    enable: true
    max: 15
  LR_scheduler:
    enable: true
    patience: 5
    factor: 0.5
    min_lr: 1e-6
  gradient_clipping: # éviter que les gradients deviennent trop grands.
    enable: true
    value: 1.0
  weight_decay: # régularisation pour éviter le surapprentissage.
    enable: true
    value: 1e-4
  optimizer: "adam"
  dropout:
    enable: true
    value: 0.1
  scheduler: # a assurer 
    enable: false
    type: "cosine"
  group_norm:
    enable: true
    num_groups: 8
  validation:
    enable: false
    percentage: 0.2

region:
  lon_min: -18
  lon_max: 0
  lat_min: 21
  lat_max: 36

dates:
  train:
    start: "1980-01-01"
    end: "1982-12-31"
  test:
    start: "1983-01-01"
    end: "1983-12-31"

paths:
  root_dir: ""
  results_dir: "./temp/results_test_app2/"
  shapefile_path: "./morocco_shapefile/morocco_unified_fixed_v2.shp"
  lmdz35_predictor_pattern: "./DATA1/lmdz_35/present_1979_1985/all_Mor/{lmdz_var}-{suffix}.nc"
  lmdz35_path: "./DATA1/predictand_lmdz/t2m_hist_ATM_DA_1979-2014_lat19to38_lon-20to1.nc"