project:
  main_config_path: "./temp/main/configs/unet/config.yaml"

metric:
  name: "bias"
  strategy: "daily_first"         # "daily_first" or "mean_first"
  return_by_year: false
  min_valid: 10
  seasons: ["Annual", "DJF", "MAM", "JJA", "SON"]

data:
  prediction_path: null           # null => auto from results/<experiment>/output_data/
  prediction_var: "air_temperature"
  prediction_units: null          # null => infer from file

  reference_path: null            # null => use cfg.target_path from main config
  reference_var: null             # null => infer automatically
  reference_units: null           # null => infer from file

time:
  use_test_period_from_main_config: true
  start_date: null
  end_date: null

output:
  save_netcdf: true
  save_summary_json: true
  save_summary_csv: true