project:
  main_config_path: "./temp/main/configs/unet/config.yaml"

metric:
  name: "cams"
  threshold_quantile: 0.10
  min_spell_length: 2
  min_valid_days: 10
  min_valid_years: 1

data:
  prediction_path: null
  prediction_var: "air_temperature"
  prediction_units: null

  reference_path: null
  reference_var: null
  reference_units: null

time:
  use_test_period_from_main_config: true
  start_date: null
  end_date: null

output:
  save_netcdf: true
  save_summary_json: true
  save_summary_csv: true