###########################################################
# UNet configuration
###########################################################

general:
  verbose: true
  experiment: "unet_temperature"
  variable: "temp"
  target: "mswt"
  src: "era5"
  model_type: "unet"
  interpolation_type: "linear"
  variables: ["z", "q", "t", "u", "v"]
  levels: [500, 700, 850, 1000]
  resolution: 2.0

training:
  learning_rate: 1e-3
  epochs: 50
  batch_size: 4 # le nombre d’exemples envoyés au modèle en une seule itération.
  loss_type: "gaussian" 
  norm_mode: "gridbox"         
  early_stopping:
    enable: true
    max: 15
  LR_scheduler:
    enable: true
    patience: 5
    factor: 0.5
    min_lr: 1e-6
  gradient_clipping: # éviter que les gradients deviennent trop grands.
    enable: true
    value: 1.0
  weight_decay: # régularisation pour éviter le surapprentissage.
    enable: true
    value: 1e-4
  optimizer: "adamw"
  dropout:
    enable: true
    value: 0.1
  scheduler: # a assurer 
    enable: false
    type: "cosine"
  group_norm:
    enable: true
    num_groups: 32
  validation:
    enable: true
    pecentage: 0.2

region:
  lon_min: -18
  lon_max: 0
  lat_min: 21
  lat_max: 36

  train:
    start: "1980-01-01"
    end: "2005-12-31"
  test:
    start: "2006-01-01"
    end: "2020-12-31"

paths:
  root_dir: ""
  results_dir: "./temp/results_test/"
  shapefile_path: "./morocco_shapefile/morocco_unified_fixed_v2.shp"
  era5_predictor_pattern: "./DATA1/predictors_era5/{var}_1979-2020_levels.nc"
  mswt_path: "./DATA1/predictand_mswet/mswt_1979_2020.nc"
