###########################################################
# UNet configuration
###########################################################

general:
  verbose: true
  experiment: "unet_temperature"
  variable: "temp"
  target: "mswt"
  src: "era5"
  model_type: "unet"
  interpolation_type: "linear"
  variables: ["z", "q", "t", "u", "v"]
  levels: [500, 700, 850, 1000]
  resolution: 2.0

training:
  learning_rate: 1e-3
  epochs: 5
  batch_size: 4
  loss_type: "gaussian"
  norm_mode: "gridbox"
  early_stopping_max: 15

region:
  lon_min: -18
  lon_max: 0
  lat_min: 21
  lat_max: 36

dates:
  train:
    start: "1984-01-01"
    end: "1984-01-31"
  test:
    start: "2006-01-01"
    end: "2006-01-15"

paths:
  root_dir: ""
  results_dir: "./temp/results/"
  shapefile_path: "./morocco_shapefile/morocco_unified_fixed_v2.shp"
  era5_predictor_pattern: "./DATA1/predictors_era5/{var}_1979-2020_levels.nc"
  mswt_path: "./DATA1/predictand_mswet/mswt_1979_2020.nc"


